import type { Metadata } from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets:['latin'],
  display: "swap"
}); 


export const metadata: Metadata = {
  title: "Fatur's Portofolio",
  description: "Generated by Muhamad Faturrahman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
